version: '3'
services:
  db:
    image: postgres
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: 'trust'
      POSTGRES_PASSWORD: 'postgres'
  app:
    build: .
    command: puma -C config/puma.rb
    tty: true
    stdin_open: true
    depends_on:
      - db
    volumes:
      - .:/Biitos
      - tmp-data:/Biitos/tmp
      - public-data:/Biitos/public
  nginx:
    build:
      context: ./containers/nginx
    volumes:
      - public-data:/Biitos/public
      - tmp-data:/Biitos/tmp
    ports:
      - 80:80
    depends_on:
      - app
volumes:
  public-data:
  tmp-data:
  postgresql-data:
    driver: local
